const products = [
  {
    id: 1,
    name: "Nike Running Shoes",
    gender: "Men",
    category: "Shoes",
    price: 120,
    brand: "Nike",
    discription: "High-performance running shoes designed for comfort and speed.  Featuring lightweight materials and advanced cushioning technology for a smooth ride. Perfect for both casual runners and serious athletes.",
    image:"/nikeshoes.jpeg" },
  {
    id: 2,
    name: "Adidas Hoodie",
    gender: "Women",
    category: "Clothing",
    price: 80,
    brand: "Adidas",
    discription: "Stylish and comfortable hoodie perfect for casual wear. Made with soft, breathable fabric to keep you cozy. Available in various sizes and colors.",
    image: "/hoodies1.jpeg",
  },
  {
    id: 3,
    name: "Puma Sneakers",
    gender: "Men",
    category: "Shoes",
    price: 90,
    brand: "Puma",
    discription: "Trendy sneakers with excellent cushioning and support.  Ideal for everyday wear or workouts. Available in various sizes and colors.",
    image: '/puma.jpeg',
  },
  {
    id: 4,
    name: "Under Armour Shorts",
    gender: "Men",
    category: "Clothing",
    price: 65,
    brand: "Under Armour",
    discription: "Lightweight and breathable shorts for active wear. Perfect for workouts or casual outings. Available in various sizes and colors.",
    image: "/shorts.jpeg",
  },
    {
    id: 5,
    name: "Adidas Hoodie",
    gender: "Men",
    category: "Clothing",
    price: 40,
    brand: "Adidas",
    discription: "Comfortable and stylish hoodie for everyday wear, Perfect for layering or casual outings. available in various sizes and colors.",
    image: "/hoodies.jpeg",
  },
  
   
{
    id: 6,
    name: "Reebok Training Shoes",
    gender: "Unisex",
    category: "Shoes",
    price: 85,
    brand: "Reebok",
    description: "Durable training shoes ideal for gym sessions and cross-training. Lightweight with excellent grip and comfort.",
    image: "/download.webp",
  },
  {
    id: 7,
    name: "Converse Chuck Taylor",
    gender: "Unisex",
    category: "Shoes",
    price: 65,
    brand: "Converse",
    description: "Timeless canvas sneakers known for their iconic look and versatility. Great for everyday casual wear.",
    image: "/image1.webp",
  },
  {
    id: 8,
    name: "New Balance 574",
    gender: "Men",
    category: "Shoes",
    price: 100,
    brand: "New Balance",
    description: "Retro-inspired running shoes with ENCAP midsole cushioning for all-day comfort and style.",
    image: "/OIP.webp",
  },
  {
    id: 9,
    name: "Skechers Go Walk",
    gender: "Women",
    category: "Shoes",
    price: 70,
    brand: "Skechers",
    description: "Ultra-light slip-on walking shoes featuring high-rebound cushioning and breathable materials. Ideal for travel and daily wear.",
    image: "/OIP (1).webp",
  },
  {
    id: 10,
    name: "Under Armour Shorts",
    gender: "Women",
    category: "Clothing",
    price: 45,
    brand: "Under Armour",
    discription: "Durable and lightweight shorts for workouts. Ideal for running, training, or casual outings. Made with moisture-wicking fabric to keep you dry and comfortable.",
    image: "/shorts1.jpeg",
  },
];

export default products;
